### PR TITLE
update Docs for Catalyst

### PR DESCRIPTION
**Pull request by isaacsas**

### CODE REVIEW

**Comment by isaacsas** [comment]
Not sure the issue here; it builds fine locally.

**Comment by isaacsas** [comment]
Only thing I've been able to resolve is that the issue is not present on newer Documenter.jl versions (i.e. latest v.25 releases).

**Comment by ChrisRackauckas** [comment]
I don't think we need the using Catalyst in these docs. I think that might just be a relic.

**Comment by ChrisRackauckas** [comment]
The issue seems to just be netlify. Fingers crossed.

**Comment by isaacsas** [comment]
It may be a general v.24 issue; I get a local failure with the same error on v24.11. Unfortunately the error message is not helpful to what the issue is.

**Pull request merged**
