### PR TITLE
update docs for stochastic iterated integrals

### PR DESCRIPTION
**Pull request by frankschae**
Should be merged after https://github.com/SciML/StochasticDiffEq.jl/pull/459.

@fkastner It would be great if you could quickly review this as well  :)

### CODE REVIEW

**Comment by fkastner** [comment]
What do you think about this:


## Iterated integral approximations
The difficulty of higher strong order integrators stems from the presence of iterated stochastic integrals
```math
I(h) = \int_0^h\int_0^sdW^1_tdW^2_s
```
in these schemes.

The approximation of these iterated integrals can be avoided, if the diffusion matrix satisfies the special commutativity condition given [above](@ref special noise forms).
Because of this, many methods are only applicable to problems that satisfy the commutativity condition.

However, the methods for general SDEs, like `RKMilGeneral`, perform a direct
approximation of the iterated integrals. For those methods, the algorithms have
an `ii_approx` keyword argument which allows to specify the method for the
approximation. The choices are:
- `IICommutative`: a simplification of the integral which assumes the noise commutativity
  property. If used on a non-commutative noise problem this will limit the strong convergence
  to 0.5.
- `IILevyArea`: computes the iterated integrals based on an approximation of the Levy area
  using the [LevyArea.jl](https://github.com/stochastics-uni-luebeck/LevyArea.jl) package:
  Kastner, F. and Rößler, A., [arXiv: 2201.08424](https://arxiv.org/abs/2201.08424)
  Kastner, F. and Rößler, A., LevyArea.jl, [10.5281/ZENODO.5883748](https://zenodo.org/record/5883749#.Yg-d698xmu4).
  The package supports the schemes: `Fourier()`, `Milstein()`, `Wiktorsson()`,`MronRoe()`.
  The optimal algorithm is automatically selected based on the dimension of the Brownian
  process and the step size. By passing a specific scheme, e.g. `ii_approx=Fourier()`
  methods can be manually selected.

Example: `RKMilGeneral(;ii_approx=IILevyArea())`.

**Comment by fkastner** [comment]
Maybe also mention that it doesn't play nice with adaptivity?
Actually, what does it do if I try to use the adaptive methods with the Levy areas? Does it error?

**Comment by frankschae** [comment]
It computes an error estimate as for the corresponding commutative noise case:
`RKMilGeneral()`:
https://github.com/SciML/StochasticDiffEq.jl/blob/c802f6ec6a8cb06e0d5797fc7605d7cb85fb9e25/src/perform_step/low_order.jl#L493
`RKMilCommute()`:
https://github.com/SciML/StochasticDiffEq.jl/blob/c802f6ec6a8cb06e0d5797fc7605d7cb85fb9e25/src/perform_step/low_order.jl#L368

I need to check again what this means in practice. Could it be that it keeps decreasing the step size and then throws an error? @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
The issue is that if a step is rejected you won't be guaranteed something that "keeps" the values at `t + dt`, so it will likely be biased in some way. The commutative noise cases have extra stuff to handle this, but the Levy area approximations take random numbers that do no respect the random numbers taken in a previous rejected step (and it's not trivial to see how that would be done). It's hard to know how much bias it really introduces in practice, it depends on how aggressive the PI controller is and how many step rejections you're getting, so it's worth documenting as something that could potentially occur.

**Comment by frankschae** [comment]
Did some short tests. At least, easy examples like:
```julia

using StochasticDiffEq, Random, Test

u₀ = [0.0,0.0,0.0]
f(u,p,t) = [0.0,0.0,0.0]
g(u,p,t) = [1.0 0.0;0.0 1.0;0.0 u[1]]
dt = 1//2^8
tspan = (0.0,1.0)
prob = SDEProblem(f,g,u₀,(0.0,1.0); noise_rate_prototype=zeros(3,2))

sol = solve(prob, RKMilGeneral(;ii_approx=IICommutative()), dt=dt, adaptive=true)
@test sol.retcode == :Success
@show sol.t
sol1 = solve(prob, RKMilGeneral(;ii_approx=IILevyArea()), dt=dt, adaptive=true)
@test sol1.retcode == :Success
@show sol1.t == sol.t  # True
```
result in the same stepping behavior.

**Comment by ChrisRackauckas** [comment]
Yeah, the standard PI in that repo is tuned so that rejections are minimized. We know for example that RSwM2 is an approximation that isn't correct in theory, but in practice we haven't found a test that could solidly detect that 😅.

**Pull request merged**
