### PR TITLE
Update RegularJumps documentation for the matrix-free style

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
@TorkelE @isaacsas this was updated awhile ago, but never got upstreamed into DiffEqBio, but now is the time to probably handle it. (This is what throws the warning: it has a fallback so DiffEqBio still works, just not optimally)

### CODE REVIEW

**Comment by isaacsas** [comment]
We can make sure to use the updated version in the new DEBio version. In MT, does it make sense to create a separate `RegularJumpSystem` instead of trying to mix them with the other jump types? We could always add a conversion function between the two I'd think.

**Comment by ChrisRackauckas** [comment]
Yeah, it would make sense to make a `RegularJumpSystem` in DiffEqBio and conversions to it which generates the whole system as regular jumps. This will then give us a playground to start working on more refined conversions, like `MixedRegularSSA` that has both versions of the jumps and sets up the parameters in a nice way to allow switching between the two when `x<switch`, and possibly make this as a whole ODEProblem with a second switch, etc. Which is then incentive to get the tau-leaping into StochasticDiffEq and start doing all sorts of cool things... Basically `RegularJumpSystem` will be a great stepping stone, so I'd love to have it.

**Comment by isaacsas** [comment]
Yeah, heading towards hybrid system representations was exactly my thought too.

**Comment by isaacsas** [comment]
Once we get jumpsystems, dep graphs, and conversions from reaction systems for jumps, I’ll add reg jump systems (if no one else has looked at it by that point). That will give parity with the current DEBio functionality I think...

**Pull request merged**
