### PR TITLE
strict cross references and links

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by ArnoStrouwen** [comment]
Why does Documenter not run on these?

**Comment by ChrisRackauckas** [comment]
Buildkite only launches on branches, not forks.

**Comment by ArnoStrouwen** [comment]
> Buildkite only launches on branches, not forks.

Then why does buildkite run on PRs to SciMLDocs? e.g. https://buildkite.com/julialang/scimldocs/builds/641 from
https://github.com/SciML/SciMLDocs/pull/146

**Comment by ChrisRackauckas** [comment]
I'm not sure.

**Comment by ArnoStrouwen** [comment]
Is there a way to get the same buildkite behavior on PRs here, like at SciMLDocs, @thazhemadam ?

**Comment by ArnoStrouwen** [comment]
@thazhemadam did you ever figure out why buildkite does not run on PRs here? I can't find anything different in the buildkite settings here compared to SciMLDocs.

**Pull request merged**
