### PR TITLE
Update noise_process.md

### PR DESCRIPTION
**Pull request by FelixNoessler**
Hello,

the link to  ``DiffEqNoiseProcess.jl`` was broken. I added the link to documentation of that package (or should instead a link to the github page be used?).

Best,
Felix

### CODE REVIEW

**Comment by FelixNoessler** [comment]
thanks, that was quick!

**Comment by ChrisRackauckas** [comment]
Thank you!

**Comment by FelixNoessler** [comment]
Can you also change the link in the about section on Github [https://github.com/SciML/DiffEqNoiseProcess.jl](https://github.com/SciML/DiffEqNoiseProcess.jl)

from [noise.sciml.ai/](https://noise.sciml.ai/) to 
[ https://docs.sciml.ai/DiffEqNoiseProcess/]( https://docs.sciml.ai/DiffEqNoiseProcess/)?

**Comment by ChrisRackauckas** [comment]
Done

**Pull request merged**
