### PR TITLE
Docs for Catalyst

### PR DESCRIPTION
**Pull request by isaacsas**

### CODE REVIEW

**Comment by isaacsas** [comment]
Before merging this will require new releases of Catalyst, ModelingToolkit and DiffEqProblemLibrary (as of 7/14).

**Comment by isaacsas** [comment]
@ChrisRackauckas @TorkelE OK, I've re-read and am happy with this. If you have more comments let me know, otherwise I think this is good for the switch.

**Comment by TorkelE** [comment]
No additional comments from me.

**Comment by isaacsas** [comment]
Closing since we've migrated these to Catalyst. I'll try to put in a PR to remove the DEBio docs in the next few days, along with updating any DEBio refs to point to Catalyst.

**Pull request closed without merging**
