### PR TITLE
add strange attractor odes

### PR DESCRIPTION
**Pull request by anandijain**
will this just work or do i need to change a compat somewhere

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
That should work.

**Comment by anandijain** [comment]
does it need a diffeq version bump to deploy? if so lets i'd opt to wait for other stuff rather than patch for this

**Comment by ChrisRackauckas** [comment]
it'll be on dev.

**Comment by anandijain** [comment]
https://github.com/SciML/DiffEqDocs.jl/runs/3625228913#step:5:16 https://diffeq.sciml.ai/dev/types/ode_types/ 
hmm seems like its missing the docstrings, but i don't see anything obviously wrong

**Pull request merged**
